# Generated by Django 5.1.6 on 2025-02-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='verified',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
