# Generated by Django 5.1.6 on 2025-02-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_app', '0003_webhooklog_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
