# Generated by Django 5.1.6 on 2025-02-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_app', '0004_webhooklog_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
